=== hallu-boss/AutoCal/processor/app/planvalidation/s-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "year",
    "t1",
    "t2",
    "t3",
    "t4",
    "t5",
    "t6",
    "t7",
    "t8",
    "t9",
    "t10",
    "t11",
    "t12",
    "t13",
    "t14",
    "t15"
  ],
  "properties": {
    "year": {
      "type": "integer"
    },
    "t1": { "$ref": "#/definitions/weekDates" },
    "t2": { "$ref": "#/definitions/weekDates" },
    "t3": { "$ref": "#/definitions/weekDates" },
    "t4": { "$ref": "#/definitions/weekDates" },
    "t5": { "$ref": "#/definitions/weekDates" },
    "t6": { "$ref": "#/definitions/weekDates" },
    "t7": { "$ref": "#/definitions/weekDates" },
    "t8": { "$ref": "#/definitions/weekDates" },
    "t9": { "$ref": "#/definitions/weekDates" },
    "t10": { "$ref": "#/definitions/weekDates" },
    "t11": { "$ref": "#/definitions/weekDates" },
    "t12": { "$ref": "#/definitions/weekDates" },
    "t13": { "$ref": "#/definitions/weekDates" },
    "t14": { "$ref": "#/definitions/weekDates" },
    "t15": { "$ref": "#/definitions/weekDates" }
  },
  "definitions": {
    "weekDates": {
      "type": "array",
      "minItems": 5,
      "maxItems": 5,
      "items": {
        "type": "string"
      }
    }
  }
}

=== hallu-boss/AutoCal/cli/data/schedule.json
{
    "year": 2025,
    "t1":  ["03.03", "04.03", "05.03", "06.03", "07.03"],
    "t2":  ["10.03", "11.03", "12.03", "13.03", "14.03"],
    "t3":  ["17.03", "18.03", "19.03", "20.03", "21.03"],
    "t4":  ["24.03", "25.03", "26.03", "27.03", "28.03"],
    "t5":  ["31.03", "01.04", "02.04", "03.04", "04.04"],
    "t6":  ["07.04", "08.04", "09.04", "10.04", "11.04"],
    "t7":  ["28.04", "15.04", "16.04", "17.04", "14.04"],
    "t8":  ["05.05", "29.04", "23.04", "24.04", "25.04"],
    "t9":  ["12.05", "06.05", "30.04", "08.05", "09.05"],
    "t10": ["19.05", "13.05", "07.05", "15.05", "16.05"],
    "t11": ["26.05", "20.05", "14.05", "22.05", "23.05"],
    "t12": ["02.06", "27.05", "21.05", "29.05", "30.05"],
    "t13": ["09.06", "03.06", "28.05", "05.06", "06.06"],
    "t14": ["16.06", "10.06", "04.06", "12.06", "13.06"],
    "t15": ["23.06", "17.06", "11.06", "18.06", "24.06"]
}
