=== hallu-boss/AutoCal/processor/app/planvalidation/t-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  "properties": {
    "Monday": { "$ref": "#/definitions/daySchedule" },
    "Tuesday": { "$ref": "#/definitions/daySchedule" },
    "Wednesday": { "$ref": "#/definitions/daySchedule" },
    "Thursday": { "$ref": "#/definitions/daySchedule" },
    "Friday": { "$ref": "#/definitions/daySchedule" }
  },
  "definitions": {
    "daySchedule": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["title", "type", "time", "occurrences"],
        "properties": {
          "title": { "type": "string" },
          "type": { "type": "string" },
          "time": {
            "type": "object",
            "required": ["start", "end"],
            "properties": {
              "start": {
                "type": "string",
                "pattern": "^[0-2][0-9]:[0-5][0-9]$"
              },
              "end": { "type": "string", "pattern": "^[0-2][0-9]:[0-5][0-9]$" }
            }
          },
          "occurrences": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== hallu-boss/AutoCal/cli/data/timetable.json
{
  "Monday": [
    {
      "title": "Podstawy Programowania I",
      "type": "lecture",
      "time": {
        "start": "10:15",
        "end": "12:45"
      },
      "occurrences": "1,3,6,7"
    },
    {
      "title": "ZPI",
      "type": "labs",
      "time": {
        "start": "13:15",
        "end": "15:45"
      },
      "occurrences": "7,8"
    }
  ],
  "Tuesday": [
    {
      "title": "AAA",
      "type": "lecture",
      "time": {
        "start": "10:15",
        "end": "12:45"
      },
      "occurrences": "7"
    }
  ],
  "Wednesday": [],
  "Thursday": [],
  "Friday": []
}
